import { chromium } from "playwright";
const KEY = process.env.KEY, SEC = process.env.SEC;
const browser = await chromium.launch();
const ctx = await browser.newContext({ extraHTTPHeaders: { Authorization: `token ${KEY}:${SEC}` }, viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage(); const errs=[]; page.on("pageerror", e=>errs.push(String(e)));
await page.goto("https://crm.marcosbarbosagroup.com/hoy", { waitUntil: "networkidle" });
await page.locator(".tabs button", { hasText: "Pipeline" }).click();
await page.waitForSelector(".deal, .empty");
await page.locator("button.ghost", { hasText: "Nuevo negocio" }).click();
await page.waitForSelector(".drawer .form");
await page.fill('.field:has-text("Empresa") input', "ZZ Negocio Prueba");
await page.fill('.field:has-text("Contacto") input', "Carlos Test");
await page.fill('.field:has-text("Valor") input', "1500000");
await page.fill('.field:has-text("Cierre estimado") input', "2026-11-15");
await page.fill('.field:has-text("Próximo paso") input', "Enviar presupuesto");
await page.screenshot({ path: "shot-deal-form.png" });
await page.locator("button.btn-primary", { hasText: "Crear negocio" }).click();
await page.waitForTimeout(1200);
console.log("deals:", await page.locator(".deal").count());
await page.screenshot({ path: "shot-deal-card.png", fullPage: true });
console.log("pageerrors:", errs.length?errs:"(none)");
await browser.close(); console.log("done");
